[package]
name = "gh-utils-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
git2 = "0.19.0"
octocrab = "0.39.0"
parquet = "52.2.0"
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }
walkdir = "2.5.0"
